### ISSUE TITLE
/dev/NULL is not a valid Linux file (use /dev/null instead)

### ISSUE THREAD

**Issue by nuena** [krakenrf/heimdall_daq_fw#1]
**Description:**

The three Shell scripts `daq_start_sm.sh daq_synthetic_start.sh unit_test.sh` redirect some error messages to /dev/NULL. This file does not exist in Ubuntu, and in no other operating system I know of. Windows uses NUL but that's not meant here. 

The null device in Ubuntu is `/dev/null`. 

**Current Behaviour:** 

A redirection to `/dev/NULL` will fail with an error message unless called with root-privileges. If called as root, a new text file will be created (or an existing one overwritten), which, while not causing huge issues, is not desired.

**Resolution:**

Change all redirections to `/dev/null`.

**Comment by krakenrf** [comment]
Thank you for your warning, problem and solution description. 
I have updated accordingly the currently active branch (development).
