### ISSUE TITLE
Manual Install - Fails at the cmake command.

### ISSUE THREAD

**Issue by KD7CAO** [krakenrf/heimdall_daq_fw#14]
When running this install script in process, I get the output below the script. Ubuntu 22.04 LTS install. (Looking for alternatives to Raspi4.) Output files attached as well.
cd
git clone https://github.com/krakenrf/kfr
cd kfr
mkdir build
cd build
**cmake -DENABLE_CAPI_BUILD=ON -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release ..**
make

- The CXX compiler identification is Clang 14.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ - broken
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/usr/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/kd7cao/kfr/build/kfr/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_8e768/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_8e768.dir/build.make CMakeFiles/cmTC_8e768.dir/build
    gmake[1]: Entering directory '/home/kd7cao/kfr/build/kfr/build/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_8e768.dir/testCXXCompiler.cxx.o
    /usr/bin/clang++    -MD -MT CMakeFiles/cmTC_8e768.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_8e768.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_8e768.dir/testCXXCompiler.cxx.o -c /home/kd7cao/kfr/build/kfr/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    Linking CXX executable cmTC_8e768
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8e768.dir/link.txt --verbose=1
    /usr/bin/clang++ CMakeFiles/cmTC_8e768.dir/testCXXCompiler.cxx.o -o cmTC_8e768 
    /usr/bin/ld: cannot find -lstdc++: No such file or directory
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    gmake[1]: *** [CMakeFiles/cmTC_8e768.dir/build.make:100: cmTC_8e768] Error 1
    gmake[1]: Leaving directory '/home/kd7cao/kfr/build/kfr/build/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:127: cmTC_8e768/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:19 (project)

-- Configuring incomplete, errors occurred!
See also "/home/kd7cao/kfr/build/kfr/build/CMakeFiles/CMakeOutput.log".
See also "/home/kd7cao/kfr/build/kfr/build/CMakeFiles/CMakeError.log".

[CMakeError.log](https://github.com/krakenrf/heimdall_daq_fw/files/10659683/CMakeError.log)

[CMakeOutput.log](https://github.com/krakenrf/heimdall_daq_fw/files/10659684/CMakeOutput.log)

**Comment by krakenrf** [comment]
> -- Check for working CXX compiler: /usr/bin/clang++ - broken

I think this is the issue someone else saw before, and it still seems like it's not fixed. Basically Ubuntu broke something with the clang packages and it's up to them to fix this. 

But meanwhile I think there is a simple solution. If you have a broken clang install just run 'sudo apt-get install g++-12', this should apparently fix it. If clang is NOT broken on your system, don't run that as we don't know if that will break other things.

**Comment by KD7CAO** [comment]
Thank you. The updated that you provided fixed it perfectly. Since this was a brand new install on a HIGOLE 1 Pro, I figured I had nothing to lose. Sorry it took a week to give it a try.

**Comment by jabowery** [comment]
Ubuntu 22.04.04 LTS still has this issue and the install of `g++-12` still overcomes the `cmake` problem.

It might be worthwhile putting something in the README about this.
