### ISSUE TITLE
How to disable AGC behaviour?

### ISSUE THREAD

**Issue by trishmapow** [krakenrf/heimdall_daq_fw#18]
Hi,
I'm using the KrakenSDR with gr-krakensdr. I have set the gains in the GNURadio block, and also in the daq_chain_config.ini.
However, in the below DAB radio recording, during the null symbol (no signal), the signal is automatically amplified. Is there a way to disable this behaviour, as it is affecting my signal processing?
Thank you.

![image](https://user-images.githubusercontent.com/17211063/234734001-5867269c-0456-415a-b46d-c3916d0bf475.png)
The expected output with a normal RTL-SDR is below.
![image](https://user-images.githubusercontent.com/17211063/234738709-e348aa8e-08c7-4d1f-a590-b26dfa039f26.png)

![image](https://user-images.githubusercontent.com/17211063/234733527-ea14c556-a6a0-4816-9b17-2339352c3588.png)

```
[meta]
ini_version = 7
config_name = kraken_default

[hw]
name = kraken5
unit_id = 0
ioo_type = 0
num_ch = 5
en_bias_tee = 0,0,0,0,0

[daq]
log_level = 5
daq_buffer_size = 262144
center_freq = 700000000
sample_rate = 2048000
gain = 496
en_noise_source_ctr = 1
ctr_channel_serial_no = 1000

[pre_processing]
cpi_size = 1048576
decimation_ratio = 1
fir_relative_bandwidth = 1.0
fir_tap_size = 1
fir_window = hann
en_filter_reset = 0

[calibration]
corr_size = 65536
std_ch_ind = 0
en_iq_cal = 1
amplitude_cal_mode = channel_power
en_gain_tune_init = 0
gain_lock_interval = 0
unified_gain_control = 0
require_track_lock_intervention = 0
cal_track_mode = 2
cal_frame_interval = 687
cal_frame_burst_size = 10
amplitude_tolerance = 2
phase_tolerance = 1
maximum_sync_fails = 10
iq_adjust_source = explicit-time-delay
iq_adjust_amplitude = 0,0,0,0
iq_adjust_time_delay_ns = 0, 0, 0, 0

[adpis]
en_adpis = 0
adpis_proc_size = 8192
adpis_gains_init = 496,496,496,496,496

[data_interface]
out_data_iface_type = eth

```

**Comment by trishmapow** [comment]
I have manually taken recordings with the kraken librtlsdr using `sudo ./rtl_sdr -f 206.352M -d 1 test_kraken_agc.bin` and that behaves correctly (as in the second picture).
I believe the issue would have to be in the DAQ system.

**Comment by petotamas** [comment]
Hi,

I believe this behaviour is rather related to the automatic, periodic calibration check than the AGC, as the built-in AGC of the chip is disabled by the rtl_daq software module upon startup.
Try to change cal_track_mode to 0 or 1, or you can increase the cal_frame_interval. 
Not sure, but I hope it helps.
