### ISSUE TITLE
eth mode not starting because variable parsed incorrectly

### ISSUE THREAD

**Issue by amatsumara** [krakenrf/heimdall_daq_fw#19]
This returns value with leading space:
https://github.com/krakenrf/heimdall_daq_fw/blob/main/Firmware/daq_start_sm.sh#L24

So this check will not pass:
https://github.com/krakenrf/heimdall_daq_fw/blob/main/Firmware/daq_start_sm.sh#L116

This seem to do the job:
`out_data_iface_type=$(awk -F'=' '/out_data_iface_type/ {gsub (" ", "", $0); print $2}' daq_chain_config.ini)`

**Comment by krakenrf** [comment]
What system are you on? As far as I've seen eth mode is working normally on the systems i've tested. But will look into this.

**Comment by amatsumara** [comment]
> What system are you on? As far as I've seen eth mode is working normally on the systems i've tested. But will look into this.

I downloaded image for RPi from here https://github.com/krakenrf/krakensdr_doa/releases/ and did all experiments using this image on RPi 4 8GB.

**Comment by krakenrf** [comment]
Added already.

**Comment by dubrsl** [comment]
`sed -n '/^out_data_iface_type/s/.*=[[:space:]]*\(.*\)[[:space:]]*$/\1/p'`
