### ISSUE TITLE
make problem

### ISSUE THREAD

**Issue by SpongeBobaa** [krakenrf/heimdall_daq_fw#22]
I encountered a slight error while using the `make` command, and I hope to receive some advice.

The following is the output after using `make`:

gcc -Wall -std=gnu99 -march=native -O2 -I. -c -o ini.o ini.c
gcc -Wall -std=gnu99 -march=native -O2 -I. -c -o log.o log.c
gcc -Wall -std=gnu99 -march=native -O2 -I. -c -o iq_header.o iq_header.c
gcc -Wall -std=gnu99 -march=native -O2 -I. -c -o sh_mem_util.o sh_mem_util.c
gcc -Wall -std=gnu99 -march=native -O2 -I. log.o ini.o iq_header.o -o rtl_daq.out rtl_daq.c -lpthread -lzmq  -L. -lrtlsdr -lusb-1.0
gcc -Wall -std=gnu99 -march=native -O2 -I. sh_mem_util.o log.o ini.o iq_header.o -o rebuffer.out rebuffer.c -lrt -lm
gcc -Wall -std=gnu99 -march=native -O2 -I. sh_mem_util.o log.o ini.o iq_header.o -o iq_server.out iq_server.c -lrt
gcc -Wall -std=gnu99 -march=native -O2 -I. -c fir_decimate.c -o fir_decimate.o
gcc -Wall -std=gnu99 -march=native -O2 -I. fir_decimate.o sh_mem_util.o log.o ini.o iq_header.o -o decimate.out -lrt -lkfr_capi
/usr/bin/ld: error: cannot find -lkfr_capi
fir_decimate.o:fir_decimate.c:function main: error: undefined reference to 'kfr_allocate'
fir_decimate.o:fir_decimate.c:function main: error: undefined reference to 'kfr_allocate'
fir_decimate.o:fir_decimate.c:function main: error: undefined reference to 'kfr_allocate'
fir_decimate.o:fir_decimate.c:function main: error: undefined reference to 'kfr_allocate'
fir_decimate.o:fir_decimate.c:function main: error: undefined reference to 'kfr_filter_create_fir_plan_f32'
fir_decimate.o:fir_decimate.c:function main: error: undefined reference to 'kfr_filter_process_f32'
fir_decimate.o:fir_decimate.c:function main: error: undefined reference to 'kfr_filter_process_f32'
collect2: error: ld returned 1 exit status
make: *** [Makefile:38: decimate_x86] Error 1

The error seems to indicate that it is related to KFR, but I have successfully installed the KFR project.

Any suggestion will be appreciated.

**Comment by dubrsl** [comment]
Hi,
Be sure that you enable CAPI in kfr.
Example how to build it:
```
        TEMPDIR=$(mktemp -d)
        git clone --branch 5.1.0 --single-branch 'https://github.com/kfrlib/kfr.git' "$TEMPDIR"
        mkdir -p "$TEMPDIR/build" && cd "$TEMPDIR/build"
        cmake -Wno-dev -GNinja -DKFR_ENABLE_CAPI_BUILD=ON -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release ..
        ninja
        mkdir -p '/usr/include/kfr'
        cp "$TEMPDIR/build/lib/"* '/usr/lib'
        cp "$TEMPDIR/include/kfr/capi.h" '/usr/include/kfr'
        ldconfig
```

**Comment by SpongeBobaa** [comment]
My previous KFR was installed under the make tool.

Although I don't know what happened, I tried the method you provided (possibly due to Ninja),

I succeeded.

Thank you very much !
