### ISSUE TITLE
More information about ic in the board

### ISSUE THREAD

**Issue by Koreko209** [krakenrf/heimdall_daq_fw#26]
Hi In krakenrf board between Individual tuner on/off DIP switched and USB Type-C DATA there are 3 identical ic,I want to know here name and what it do do and here datasheet if there 
![٢٠٢٤٠٢٠٥_١٣٠٩١٩](https://github.com/krakenrf/heimdall_daq_fw/assets/155153150/42410423-920d-4845-bd5e-dff76adfb78a)
Thanks

**Comment by krakenrf** [comment]
Replied via email previously.
