### ISSUE TITLE
README link invalid to install scripts

### ISSUE THREAD

**Issue by jabowery** [krakenrf/heimdall_daq_fw#28]
The link in this README text is invalid.

`If a premade image does not exist for your computing device, you can use one of our install scripts to automate a fresh install. The script will install heimdall, and the DoA and PR DSP software automatically. Details on the Wiki at https://github.com/krakenrf/krakensdr_docs/wiki/10.-VirtualBox,-Docker-Images-and-Install-Scripts#install-scripts`

**Comment by jabowery** [comment]
https://github.com/krakenrf/krakensdr_docs/wiki/09.-VirtualBox,-Docker-Images-and-Install-Scripts#install-scripts

works

The difference is in the "09"

**Comment by krakenrf** [comment]
Fixed thanks
