### ISSUE TITLE
Repeating "Circular buffer may overrun." Warnings in rtl_daq.log

### ISSUE THREAD

**Issue by ckoval7** [krakenrf/heimdall_daq_fw#4]
```
21:30:04 WARN  rtl_daq.c:608: Circular buffer may overrun. Consider increasing the number of buffers. RTL Buff index: 3089, read_buff_ind: 3047
21:30:04 WARN  rtl_daq.c:608: Circular buffer may overrun. Consider increasing the number of buffers. RTL Buff index: 3089, read_buff_ind: 3048
21:30:04 WARN  rtl_daq.c:608: Circular buffer may overrun. Consider increasing the number of buffers. RTL Buff index: 3090, read_buff_ind: 3048
21:30:04 WARN  rtl_daq.c:608: Circular buffer may overrun. Consider increasing the number of buffers. RTL Buff index: 3090, read_buff_ind: 3048
21:30:04 WARN  rtl_daq.c:608: Circular buffer may overrun. Consider increasing the number of buffers. RTL Buff index: 3090, read_buff_ind: 3048
21:30:04 WARN  rtl_daq.c:608: Circular buffer may overrun. Consider increasing the number of buffers. RTL Buff index: 3089, read_buff_ind: 3048
21:30:04 WARN  rtl_daq.c:608: Circular buffer may overrun. Consider increasing the number of buffers. RTL Buff index: 3090, read_buff_ind: 3049
```

I'm trying to diagnose an issue where the software crashes when making adjustments to my KrakenSDR and set the log level to 2. rtl_daq.log keeps filling up with these warnings. I'm not sure if that's normal or related to my problems. Running the latest pi image on a 2GB RPi 4.

**Comment by nuena** [comment]
Yay, "my" bug. See https://github.com/krakenrf/heimdall_daq_fw/issues/3 for a more thourough explanation what's going on. 

This is likely a symptom that you have some performance issues, and the processing toolchain at some point is not able to run in real time anymore. Essentially, rtl_daq.c can't write the data fast enough to the downstream steps, so you either need to accept the data loss that you experience right now, or you need to improve performance somehow.

**Comment by krakenrf** [comment]
Is your Pi4 running any other tasks, or possibly thermal throttling? Generally even with this warning you shouldn't get any problems, but if the Pi4 is really strained it could end up causing a coherence desync.

**Comment by ckoval7** [comment]
It ended up being a power issue. The Kraken sure is hungry.

**Comment by krakenrf** [comment]
To clarify, was it that Kraken wasn't leaving enough power for the Pi4 on your supply, so it throttled?

**Comment by ckoval7** [comment]
It appears so. The power supply I was using is supposedly good for 3A per port, but it seemed to struggle regardless. I've moved to a new power supply that has a built in volt and amp meter. No issues since the upgrade.

**Comment by krakenrf** [comment]
Can I have the model number of the non-working supply? Maybe it has some total power output limit across all ports.

Want to make a note in the documentation if there are some supplies like that.

**Comment by ckoval7** [comment]
Rav Power RP-PC006 https://www.ravpower.com/products/rp-pc006-36w-usb-quick-charger
