### ISSUE TITLE
radio astronomy interferometer using GNU Radio

### ISSUE THREAD

**Issue by anthfuller** [krakenrf/heimdall_daq_fw#5]
Would you have examples for using GNU Radio to build a radio astronomy interferometer using just two of the KrakenSDR RTL-SDR coherent antennas? I've started working in GNU Radio but from my understanding the KrakenSDR isn't naturally coherent like the USRP B210 SDR module. 

Any help would or examples would help. Thank you!

**Comment by petotamas** [comment]
Hello,

On hardware level, the individual receiver channels of the KrakenSDR are running from the same clock (LO and sampling clock), so they form a coherent multichannel receiver. This firmware is responsible for the coherent data aquisition and for the calibration, thus the user can grant access to the coherently collected data and synchronized data right away with running the code.

At the moment the prepared multichannel signal can be accessed from this firmware through a TCP socket or through shared memory. GNU radio is currently not supported directly, but the implementation of the corresponding feature is in our development plan.

**Comment by anthfuller** [comment]
Unfortunately with the lengthy wait of almost a year in waiting for the KrakenSDR, and this given limitation, it would have been more beneficial for me to purchase a true coherent SDR, the USRP B210! 

No wonder several of my associates were going to the B210. The KrakenSDR's price point was a deciding factor for me. A significant amount of RTL-SDR devices support GNU Radio. I'm disappointed and won't wait for development. You know anyone interested in purchasing my KrakenSDR!

**Comment by krakenrf** [comment]
Right now I'm about 1-2 weeks away from releasing a beta GNU Radio source block for the KrakenSDR. This block will make the coherent IQ data streams from the heimdall DAQ software available in GNU Radio for further DSP processing through a socket connection.

**Comment by krakenrf** [comment]
gr-krakensdr repo: https://github.com/krakenrf/gr-krakensdr

Currently beta, please report any bugs directly to the gr-krakensdr issues.

Coherent data is output in GNU Radio, so you can treat it as if the radio were naturally coherent. You should be able to use it with other interferometer GNU Radio flowgraphs

**Comment by anthfuller** [comment]
Thank you!!

**Comment by anthfuller** [comment]
Need your help with an issue in x_corr_plot = 10*np.log10
That is part of the issues, with a divide of zero. I have an issue ticket
open. I'm trying to figure a work around and could use your help please?

https://github.com/krakenrf/krakensdr_docs/issues/9
This is on an x86 machine running Ubuntu 22.04. Below is the error code.
Thank you!!














*Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use
QT_QPA_PLATFORM=wayland to run on Wayland anyway.Sending control
messageControl interface communication finishedReconfiguration succesfully
finishedSending control messageControl interface communication
finishedReconfiguration succesfully finishedSending control messageControl
interface communication finishedReconfiguration succesfully
finished/usr/local/lib/python3.10/dist-packages/gnuradio/krakensdr/krakensdr_correlator.py:46:
RuntimeWarning: divide by zero encountered in log10x_corr_plot =
10*np.log10(np.abs(x_corr))Failed to put IQ Samples into the
QueueException:*

[image: Exception_IQ_Samples.png]


[image: KrakenSDR_Corrolation_Test.png]

Thank you!

**Comment by krakenrf** [comment]
Can you please open a new issue and upload whatever GNU Radio code you have?

RuntimeWarning: divide by zero encountered in log10x_corr_plot =
10*np.log10(np.abs(x_corr))

This isn't really an error, it's just a warning that shows at the start when the buffers are empty and full of zeros. Once they fill up it goes away.

**Comment by ChrisPannell** [comment]
Hi, I'm a little confused - is the software for GNU all working now or is it still beta? I can't see anything since October 2022.  I am considering buying the hardware, but I have had an unfortunate experience once with support fading out on something else I paid a lot of money for, and I don't want to get bitten again. 
Regards,
Chris

**Comment by krakenrf** [comment]
The block is finished, but in beta status pending more user feedback. But in my own tests on my hardware it's stable (assuming you run on powerful enough hardware). Thus far we have not heard many reports from users on it.

Development on KrakenSDR is going to continue, we're just getting back into it for 2023 now.
