### ISSUE TITLE
cleanup and packageability

### ISSUE THREAD

**Issue by rfc6919** [krakenrf/heimdall_daq_fw#8]
I'm interested in doing some work to clean up the KrakenSDR tools to make them less dependant on running on a single-function system and more palatable for distro packaging (or just running on a regular laptop without stomping over distro-provided components). Would you be receptive to PRs making these kinds of changes?

My rough plan is to start with heimdall_daq:

* Clean up build process
* Vendor in the patched support libraries librtlsdr, Ne10, KFR (don't install to system library locations)
* Patch the various processes used in DAQ to use proper service management under systemd instead of kraken_doa_start.sh just forking them off to the background of a running shell

Do you plan to get the librtlsdr changes upstreamed to remove the need for a patched version? I'm not sure about the performance cost of making whether to use zero-copy or not runtime configurable, off the top of my head that's the only bit that looks problematic.

**Comment by krakenrf** [comment]
It's a good idea but a few notes:

- A dedicated system for the Kraken heimdall code is always going to be preferred as if users run other intensive DSP or other software alongside the Kraken software, it could result in data being dropped, which would end up with coherence loss. Or if users have other high data rate USB devices plugged in (like a USB drive), it could cause USB latency issues, again resulting in drops.

- No plans to upstream the changes in librtlsdr. The changes made are detrimental for any other RTL-SDR application, so it makes no sense IMO. 
  - The first change is to disable zero-copy as it causes issue with sample alignment stability. Zero-copy is probably desired in almost all other applications for its CPU efficiency. You could make it a runtime flag, but I don't think it will get used often. There was a bug in the past Linux kernels were zerocopy was totally bugged, but it's long been fixed.
  - The second is to add PPM 'pulse' functionality for sample alignment. Useless for any other application.
  - The third is to disable a specific filter in the tuner to avoid the phase shift it causes at the edges. But again for any other application you probably want those filters on.

I think a better thing would be to just install the kraken specific librtlsdr to a separate system directory and have the code link to that.

**Comment by rfc6919** [comment]
my use case is running the tools on a laptop that's got enough grunt to do everything, which cuts what has to be carried down from kraken/rpi/battery/laptop down to just kraken/battery/laptop (and will give better life from the external battery pack for the kraken since the pi is no longer part of its load).

my in-progress does just install the patched librtlsdr to the heimdall install dir and RPATH the binaries to use that over any system-installed librtlsdr, I'll keep that strategy.

**Comment by krakenrf** [comment]
Made some changes to the install script, it now longer nukes previous librtlsdr installs now. Now it links to a local librtlsdr.a file in the _daq_core directory.
