### ISSUE TITLE
First installation on x64 with installation script

### ISSUE THREAD

**Issue by HB9IBI** [krakenrf/heimdall_daq_fw#9]
Hello all,
works great on Pi4, trying to install on a NUC Celeron 2 core with installation script 

wget https://raw.githubusercontent.com/krakenrf/krakensdr_docs/main/install_scripts/krakensdr_x86_install_doa_pr.sh
sudo chmod +x krakensdr_x86_install_doa_pr.sh
./krakensdr_x86_install_doa_pr.sh

Goes to the end (after 3h), but launching gives

root@debian:~/krakensdr_doa# ./krakensdr_doa_start.sh
-bash: ./krakensdr_doa_start.sh: No such file or directory
root@debian:~/krakensdr_doa# ./kraken_doa_start.sh
./kraken_doa_start.sh: line 4: conda: command not found
./kraken_doa_start.sh: line 5: conda: command not found
Shut down DAQ chain ..
Config file check bypassed [ WARNING ]
kernel.sched_rt_runtime_us = -1
Traceback (most recent call last):
  File "/root/krakensdr_doa/heimdall_daq_fw/Firmware/fir_filter_designer.py", line 16, in <module>
    from scipy import signal
ModuleNotFoundError: No module named 'scipy'
DAQ chain not started!
Starting KrakenSDR Direction Finder
Web Interface Running at 0.0.0.0:8080
PHP Data Out Server Running at 0.0.0.0:8081

No web page reachable at port 8080 ...

Why are shown some py stuff ?

Thank you for your great job,

Regards,
François

**Comment by krakenrf** [comment]
Did you restart after the install?

Looks like conda didn't install correctly on your machine via the script for some reason.

Can you try run `conda activate kraken` in the terminal?

**Comment by HB9IBI** [comment]
Thank you for your answer.
Yes I've restarted after installation.
Conda activate kraken run's, but nothing changed.

I've tried on 2 others PCs, exactly the same installation (last Ubuntu), and same scripts
Every installation runs till the end, after reboot, and ./kraken_doa_start.sh 
Web port 8080 gives the Kraken web pages with configuration, spectrum and DOA or NO : impossible to open web page at all

NUC5CPYH Celeron 4GB RAM, either Debian or Ubuntu -> NO
Asus notebook X554L i5, 4GB RAM, Ubuntu -> NO
HP 6000 pro Core 2, 4GB -> OK, about 2 frames/sec

Raspi4 image : OK
Virtualbox image on Dell I5 PC 16 GB RAM : OK, about 10 frames/sec

**Comment by krakenrf** [comment]
And on each machine the actual error logs always show the same problem with scipy not being installed?

```
from scipy import signal
ModuleNotFoundError: No module named 'scipy'
```

Can you try this install on a PC that isn't working, and let me know if you get any errors?

```
conda activate kraken
conda install scipy
```

And see if you get any errors?

**Comment by krakenrf** [comment]
This was most likely due to the sudo cache expiring during the install which can happen if the apt update or one of the installs is too slow. Then perhaps ignoring the prompt for the sudo password and just pressing enter.

Added a sudo hearbeat to the scripts now which hopefully fixes it.

**Comment by HB9IBI** [comment]
Many thanks for your hints. Finally i found another PC installed without problem, a NUC I3 ...
Regards,
François
